pub const IGNORED_FUNCTIONS: [&str; 34] = [
    "with_entry",             // ComboBox, ComboBoxText
    "toplevels",              // Window
    "list_toplevels",         // Window
    "default_icon_name",      // Window
    "emit_activate",          // MenuButton, ColorButton, AppChooserButton
    "is_primary",             // MenuButton
    "is_indent_for_icon",     // TreeExpander
    "default",                // RecentManager
    "must_always_show_arrow", // MenuButton
    "get",                    // AcrivateAction - probably this is static function
    "shows_arrow",            // DropDown
    "current_drop",           // DropTarget
    "emit_escape",            // https://github.com/gtk-rs/gtk4-rs/issues/870
    // TODO
    "emit_stop_search",
    "emit_previous_match",
    "emit_next_match",
    "emit_unselect_all",
    "emit_toggle_cursor_row",
    "emit_select_all",
    "emit_activate_cursor_row",
    "emit_close",
    "emit_select_cursor_item",
    "emit_toggle_cursor_item",
    "emit_unselect_all",
    "emit_select_all",
    "emit_activate_cursor_item",
    "emit_unselect_all",
    "emit_toggle_cursor_child",
    "emit_select_all",
    "emit_activate_cursor_child",
    "drag_dest_item",
    "im_context",
    "insert_prefix",
    "emit_escape",
];

pub const IGNORED_CLASSES: [&str; 69] = [
    "ATContext",
    "AssistantPage",
    "BoolFilter",
    "BuilderListItemFactory",
    "ColorChooserDialog",
    "ColumnView",
    "ColumnViewColumn",
    "DragIcon",
    "DropTargetAsync",
    "Expander",
    "FileChooserWidget",
    "FilterListModel",
    "FixedLayoutChild",
    "FlattenListModel",
    "GridLayoutChild",
    "GridView",
    "IconPaintable",
    "KeyvalTrigger",
    "Label",
    "LinkButton",
    "ListItem",
    "ListStore",
    "ListView",
    "LockButton",
    "MapListModel",
    "MessageDialog",
    "MnemonicAction",
    "MnemonicTrigger",
    "MultiSelection",
    "NamedAction",
    "NeverTrigger",
    "NoSelection",
    "NotebookPage",
    "NothingAction",
    "OverlayLayoutChild",
    "PadController",
    "PageSetupUnixDialog",
    "Paned",
    "PopoverMenu",
    "PopoverMenuBar",
    "PrintContext",
    "PrintJob",
    "PrintUnixDialog",
    "Printer",
    "SelectionFilterModel",
    "Settings",
    "Shortcut",
    "ShortcutsGroup",
    "ShortcutsShortcut",
    "ShortcutsWindow",
    "SignalAction",
    "SingleSelection",
    "SizeGroup",
    "SliceListModel",
    "SortListModel",
    "SpinButton",
    "StackPage",
    "StringFilter",
    "StringObject",
    "StringSorter",
    "TreeListModel",
    "TreeListRow",
    "TreeListRowSorter",
    "TreeSelection",
    "TreeStore",
    "Viewport",
    "Widget",
    "WidgetPaintable",
    "WindowControls",
];
